name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run JUnit tests
        run: |
          java -cp .: ../../CalculatorTest.java
        # Replace 'path/to/your/test-library.jar' with the actual path to your JUnit library
        # Replace 'CalculatorTest' with your actual test class
