name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run JUnit tests
        run: |
          javac ../../CalculatorTest.java  # Compile the Java file
          java -cp .: ../../CalculatorTest  # Run the tests
