name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: myproject  # Specify the path to your project directory

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile and Run JUnit tests
      run: |
        cd myproject
        javac -cp .:../junit-4.12.jar CalculatorTest.java
        java -cp .:../junit-4.12.jar org.junit.runner.JUnitCore CalculatorTest
